# The language file in /lang that is used
# Do not add the .yml, Only the language id

lang: en




# Automatically install updates on launch

auto_update: true





# Blocks that are allowed to be network containers
# Only works for blocks that have inventories

container_whitelist:
- CHEST
- TRAPPED_CHEST
- BARREL
- HOPPER
- DISPENSER
- DROPPER




# Notices players, that open full chests to this plugin.
# This message will only be sent once and just to players, that do not have a network.
# You can configure the message in the language file.

notice: true




# Set to CRAFT if players should be able to craft network components
# Set to ECONOMY if players should be able to buy network components using /net component

mode: CRAFT








#                                   CRAFT-Mode related settings
#                           These will be ignored when using ECONOMY mode
#                         Even if you are on ECONOMY mode, Do NOT delte this part!

#===========================================================================================================================

# Defines the maximum range, items can be teleported for each level of range.

# You can add more range upgrades to this list, but you NEED to also give them a crafting recipe to

# Must start with 0!
# Paste 2147483647 to enable interdimensional item transmission
# Values Must be between 1 and 2147483647!

range0: 25
range1: 50
range2: 100
range3: 500
range4: 2147483647 # This number means interdimensional item transmission is allowed

#===========================================================================================================================











#                                      ECONOMY related settings
#                               These will be ignored when using CRAFT mode
#                            Even if you are on CRAFT mode, Do NOT delte this part!

#===========================================================================================================================

# Costs of specific features
# Set to 0 for free and -1 for unbuyable

cost_create: 1000
cost_container_limit: 50
cost_range: 25



# Refund a Player is getting, when deleting a network
# Don't set this below the creation cost, otherwise players can dupe money.

refund_create: 0
refund_container_limit: 0
refund_range: 0



# Base values for a new network

base_container_limit: 20
base_range: 40



# Limit of upgrades, a player can buy
# Don't set this below the base_ value'

max_container_limit: 200
max_range: 500 # Note: Items won't be transmitted into unloaded chunks

#===========================================================================================================================