# The language file in /lang that is used
# Do not add the .yml, Only the language id

lang: en



# Blocks that are allowed to be network containers
# Only works for blocks that have inventories

container_whitelist:
- CHEST
- TRAPPED_CHEST
- BARREL



# Every x ticks, all networks will sort their containers
# Increase this number, if you see laggs

tickrate: 100



# Costs of specific features
# Set to 0 for free and -1 for unbuyable

cost_create: 1000
cost_container_limit: 50
cost_range: 25



# Refund a Player is getting, when deleting a network
# Don't set this below the creation cost, otherwise players can dupe money.'

refund_create: 0
refund_container_limit: 0
refund_range: 0



# Base values for a new network

base_container_limit: 20
base_range: 40



# Limit of upgrades, a player can buy
# Don't set this below the base_ value'

max_container_limit: 200
max_range: 400 # It doesn't make sense to have really far distances since chests inside unloaded chunks won't work anyway
