name: Autosort
version: '${project.version}'
main: com.quantum625.autosort.Autosort
api-version: 1.19
description: autosort plugin
commands:
  autosort:
    description: Base commmand for the Autosort Plugin
    usage: /as <options>
    aliases: as
