name: Networks
version: '${project.version}'
main: com.quantum625.networks.Main
api-version: 1.19
description: networks plugin
commands:
   network:
    description: Base commmand for the Networks Plugin
    usage: /net <options>
    aliases: net
