name: Networks
version: '1.0.1'
main: com.quantum625.networks.Main
api-version: 1.19
description: networks plugin
author: Quantum625
database: true
softdepend: [Vault, XConomy]
commands:
   network:
    description: Base commmand for the Networks Plugin
    usage: /net <options>
    aliases: [net, networks]
permissions:
  networks.use:
    description: Allows users to use and create networks they own
    default: true

  networks.admin:
    description: Base permission for all admin commands
    default: op
    children:
      networks.admin.foreign:
        description: Allows you to access foreign networks
        default: op
        children:
          networks.admin.foreign.user:
            description: Allows you to access foreign networks with user permission
            default: op
          networks.admin.foreign.owner:
            description: Allows you to access foreign networks with owner permission
            default: op





